import image1 from "../src/images/asset 21.jpeg";
import image2 from "../src/images/asset 22.jpeg";
import image3 from "../src/images/asset 23.jpeg";
import image4 from "../src/images/asset 24.jpeg";
import image5 from "../src/images/asset 27.jpeg";
import image6 from "../src/images/asset 30.jpeg";
import image7 from "../src/images/asset 31.jpeg";
import image8 from "../src/images/asset 32.jpeg";
import image9 from "../src/images/asset 40.jpeg";
import image10 from "../src/images/asset 45.jpeg";
import image11 from "../src/images/asset 42.jpeg";
import image12 from "../src/images/asset 44.jpeg";
import image13 from "../src/images/asset 46.jpeg";
import image14 from "../src/images/asset 47.jpeg";
import image15 from "../src/images/asset 43.jpeg";
import image16 from "../src/images/asset 41.jpeg";
import express from "../src/images/asset 26.svg";

export const Data = {
  products: [
    {
      id: "p1",
      name: "دمپایی زنانه مدل سایه کد 02604",
      category: "Red",
      brand: "مد و پوشاک",
      gift: "2,000",
      beforePrice: 237000,
      off: "25",
      price: 146250,
      quantity: 0,
      express: express,
      progress: 90,
      image: image1,
      link: "/page/p1",
    },
    {
      id: "p2",
      name: "کتاب دنیای سوفی اثر یوستین گوردر",
      category: "Red",
      brand: "مد و پوشاک",
      gift: "2,000",
      beforePrice: 237000,
      off: "25",
      price: 46250,
      quantity: 0,
      express: express,
      progress: 14,
      image: image2,
      link: "/page/p2",
    },
    {
      id: "p3",
      name: "ساعت هوشمند مدل HW22",
      category: "Red",
      brand: "مد و پوشاک",
      gift: "2,000",
      beforePrice: 237000,
      off: "25",
      price: 146250,
      quantity: 0,
      express: express,
      progress: 90,
      image: image3,
      link: "/page/p3",
    },
    {
      id: "p4",
      name: "پولوشرت آستین کوتاه مردانه باینت",
      category: "Red",
      brand: "مد و پوشاک",
      gift: "2,000",
      beforePrice: 237000,
      off: "25",
      price: 146250,
      quantity: 0,
      express: express,
      progress: 90,
      image: image4,
      link: "/page/p4",
    },
    {
      id: "p5",
      name: "ست شیرآلات پادرا مدل آلفا کد BX",
      category: "Red",
      brand: "مد و پوشاک",
      gift: "2,000",
      beforePrice: 237000,
      off: "25",
      price: 146250,
      quantity: 0,
      express: express,
      progress: 90,
      image: image5,
      link: "/page/p5",
    },
    {
      id: "p6",
      name: "چاقو ترامونتینا مدل 2462010",
      category: "Red",
      brand: "مد و پوشاک",
      gift: "2,000",
      beforePrice: 237000,
      off: "25",
      price: 146250,
      quantity: 0,
      express: express,
      progress: 90,
      image: image6,
      link: "/page/p6",
    },
    {
      id: "p7",
      name: "زودپز پارس استیل مدل Chef گنجایش 6 لیتر",
      category: "Red",
      brand: "مد و پوشاک",
      gift: "2,000",
      beforePrice: 237000,
      off: "25",
      price: 146250,
      quantity: 0,
      express: express,
      progress: 90,
      image: image7,
      link: "/page/p7",
    },
    {
      id: "p8",
      name: "پنکه پارس خزر مدل FSR-SHIBA",
      category: "Red",
      brand: "مد و پوشاک",
      gift: "2,000",
      beforePrice: 237000,
      off: "25",
      price: 146250,
      quantity: 0,
      express: express,
      progress: 90,
      image: image8,
      link: "/page/p8",
    },
    {
      id: "p9",
      name: "کراکت مرغ و پنیر مهمانی پمینا",
      category: "Green",
      brand: "مد و پوشاک",
      gift: "2,000",
      beforePrice: 237000,
      off: "25",
      price: 146250,
      quantity: 0,
      express: express,
      progress: 90,
      image: image9,
      link: "/page/p9",
    },
    {
      id: "p10",
      name: "جو دو سر پرک فوری هاتی کارا",
      category: "Green",
      brand: "مد و پوشاک",
      gift: "2,000",
      beforePrice: 237000,
      off: "25",
      price: 146250,
      quantity: 0,
      express: express,
      progress: 90,
      image: image10,
      link: "/page/p10",
    },
    {
      id: "p11",
      name: "پودر کیک وانیلی زر ماکارونی",
      category: "Green",
      brand: "مد و پوشاک",
      gift: "2,000",
      beforePrice: 237000,
      off: "25",
      price: 146250,
      quantity: 0,
      express: express,
      progress: 90,
      image: image11,
      link: "/page/p11",
    },
    {
      id: "p12",
      name: "اسپری چند منظوره دامستوس",
      category: "Green",
      brand: "مد و پوشاک",
      gift: "2,000",
      beforePrice: 237000,
      off: "25",
      price: 146250,
      quantity: 0,
      express: express,
      progress: 90,
      image: image12,
      link: "/page/p12",
    },
    {
      id: "p13",
      name: "شیر پرچرب دومینو - 1 لیتر بسته 4 عددی",
      category: "Green",
      brand: "مد و پوشاک",
      gift: "2,000",
      beforePrice: 237000,
      off: "25",
      price: 146250,
      quantity: 0,
      express: express,
      progress: 90,
      image: image13,
      link: "/page/p13",
    },
    {
      id: "p14",
      name: "پنیر پیتزا مطهر - 2 کیلوگرم",
      category: "Green",
      brand: "مد و پوشاک",
      gift: "2,000",
      beforePrice: 237000,
      off: "25",
      price: 146250,
      quantity: 0,
      express: express,
      progress: 90,
      image: image14,
      link: "/page/p14",
    },
    {
      id: "p15",
      name: "خمیر هزارلا پمینا - 400 گرم",
      category: "Green",
      brand: "مد و پوشاک",
      gift: "2,000",
      beforePrice: 237000,
      off: "25",
      price: 146250,
      quantity: 0,
      express: express,
      progress: 90,
      image: image15,
      link: "/page/p15",
    },
    {
      id: "p16",
      name: "صابون فاکس Flower بسته 6 عددی",
      category: "Green",
      brand: "مد و پوشاک",
      gift: "2,000",
      beforePrice: 237000,
      off: "25",
      price: 146250,
      quantity: 0,
      express: express,
      progress: 90,
      image: image16,
      link: "/page/p16",
    },
    // itemsRed: [
    //   {
    //     cover: red1,
    //     title: "دمپایی زنانه مدل سایه کد 02604",
    //     brand: "مد و پوشاک",
    //     gift: "2,000",
    //     beforePrice: "237,000",
    //     off: "25",
    //     price: "146,250",
    //     express: express,
    //     progress: 90,
    //     link: "/page/r1",
    //   },
    //   {
    //     cover: red2,
    //     title: "کتاب دنیای سوفی اثر یوستین گوردر",
    //     brand: "کتاب، لوازم تحریر و هنر",
    //     gift: "2,000",
    //     beforePrice: "142,000",
    //     off: "68",
    //     price: "45,000",
    //     express: express,
    //     progress: 1,
    //     link: "/page/r2",
    //   },
    //   {
    //     cover: red3,
    //     title: "ساعت هوشمند مدل HW22",
    //     brand: "مد و پوشاک",
    //     beforePrice: "440,000",
    //     off: "10",
    //     price: "396,000",
    //     progress: 20,
    //     link: "/page/r3",
    //   },
    //   {
    //     cover: red4,
    //     title: "پولوشرت آستین کوتاه مردانه باینت",
    //     brand: "مد و پوشاک",
    //     beforePrice: "179,000",
    //     off: "11",
    //     price: "159,000",
    //     progress: 80,
    //     link: "/page/r4",
    //   },
    //   {
    //     cover: red5,
    //     title: "ست شیرآلات پادرا مدل آلفا کد BX",
    //     brand: "شیرآلات پادرا",
    //     beforePrice: "2,275,000",
    //     off: "10",
    //     price: "2,047,500",
    //     progress: 85,
    //     link: "/page/r5",
    //   },
    //   {
    //     cover: red6,
    //     title: "چاقو ترامونتینا مدل 2462010",
    //     brand: "خانه و آشپزخانه",
    //     beforePrice: "338,000",
    //     off: "6",
    //     price: "318,000",
    //     progress: 55,
    //     link: "/page/r6",
    //   },
    //   {
    //     cover: red7,
    //     title: "زودپز پارس استیل مدل Chef گنجایش 6 لیتر",
    //     brand: "خانه و آشپزخانه",
    //     gift: "20,000",
    //     beforePrice: "2,431,000",
    //     off: "3",
    //     price: "2,338,070",
    //     progress: 63,
    //     link: "/page/r7",
    //   },
    //   {
    //     cover: red8,
    //     title: "پنکه پارس خزر مدل FSR-SHIBA",
    //     brand: "خانه و آشپزخانه",
    //     beforePrice: "1,989,500",
    //     off: "3",
    //     price: "1,929,500",
    //     progress: 70,
    //     link: "/page/r8",
    //   },
    // ],
    // itemsGreen: [
    //   {
    //     cover: green1,
    //     title: "کراکت مرغ و پنیر مهمانی پمینا",
    //     brand: "پمینا",
    //     gift: "3,400",
    //     beforePrice: "115,000",
    //     off: "6",
    //     price: "108,500",
    //     progress: 65,
    //     link: "/page/g1",
    //   },
    //   {
    //     cover: green2,
    //     title: "جو دو سر پرک فوری هاتی کارا",
    //     brand: "ماتی کارا",
    //     beforePrice: "28,900",
    //     gift: "1,000",
    //     off: "10",
    //     price: "25,900",
    //     express: express,
    //     progress: 35,
    //     link: "/page/g2",
    //   },
    //   {
    //     cover: green3,
    //     title: "پودر کیک وانیلی زر ماکارونی",
    //     brand: "زر ماکارونی",
    //     gift: "1,000",
    //     beforePrice: "21,300",
    //     off: "67",
    //     price: "6,500",
    //     progress: 20,
    //     link: "/page/g3",
    //   },
    //   {
    //     cover: green4,
    //     title: "اسپری چند منظوره دامستوس",
    //     brand: "دامستوس",
    //     beforePrice: "38,000",
    //     off: "5",
    //     price: "36,100",
    //     express: express,
    //     progress: 46,
    //     link: "/page/g4",
    //   },
    //   {
    //     cover: green5,
    //     title: "شیر پرچرب دومینو - 1 لیتر بسته 4 عددی",
    //     brand: "دومینو",
    //     beforePrice: "38,000",
    //     off: "5",
    //     price: "36,100",
    //     express: express,
    //     progress: 78,
    //     link: "/page/g5",
    //   },
    //   {
    //     cover: green6,
    //     title: "پنیر پیتزا مطهر - 2 کیلوگرم",
    //     brand: "مطهر",
    //     gift: "1,600",
    //     beforePrice: "60,000",
    //     off: "10",
    //     price: "52,400",
    //     express: express,
    //     progress: 80,
    //     link: "/page/g6",
    //   },
    //   {
    //     cover: green7,
    //     title: "خمیر هزارلا پمینا - 400 گرم",
    //     brand: "پمینا",
    //     gift: "1,000",
    //     beforePrice: "32,900",
    //     off: "6",
    //     price: "32,000",
    //     progress: 10,
    //     link: "/page/g7",
    //   },
    //   {
    //     cover: green8,
    //     title: "صابون فاکس Flower بسته 6 عددی",
    //     brand: "فاکس",
    //     beforePrice: "34,650",
    //     gift: "1,200",
    //     off: "2",
    //     price: "33,850",
    //     express: express,
    //     progress: 20,
    //     link: "/page/g8",
    //   },
    // ],
  ],
};
// export default Data;

export const allProduct = () => {
  return Data.products;
};
